<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Services\ChatService.txt" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Services\AuthService.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Data\messages.txt" />
    <Content Include="Data\users.txt" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\avatars\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.18.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
  </ItemGroup>

</Project>
